[color-theme]
name = ""

[color-theme.base]
white = "#eee"
black = "#333"
grey = "#555"
blue = "#61AFEF"
red = "#E06C75"
yellow = "#E5C07B"
orange = "#D19A66"
green = "#98C379"
purple = "#C678DD"
cyan = "#56B6C2"
magenta = "#C678DD"

[color-theme.syntax]
attribute = "$yellow"
builtinType = "$cyan"
comment = "#5C6370"
constant = "$yellow"
constructor = "$yellow"
embedded = "$cyan"
enum = "$yellow"
enum-member = "$red"
enumMember = "$red"
escape = "$cyan"
field = "$red"
function = "$blue"
"function.method" = "$blue"
interface = "$yellow"
keyword = "$purple"
"keyword.control" = "$purple"
method = "$blue"
number = "$yellow"
property = "$red"
"punctuation.delimiter" = "$yellow"
selfKeyword = "$purple"
string = "$green"
"string.escape" = "$cyan"
struct = "$yellow"
structure = "$yellow"
symbol = "$yellow"
tag = "$blue"
"text.reference" = "$yellow"
"text.title" = "$orange"
"text.uri" = "$cyan"
type = "$yellow"
"type.builtin" = "$cyan"
typeAlias = "$yellow"
variable = "$red"
"variable.other.member" = "$green"

[color-theme.ui]
"activity.background" = "#777"
"activity.current" = "$black"
"completion.background" = "#777"
"completion.current" = "#222"
"editor.background" = "#222"
"editor.caret" = "#528BFF"
"editor.current_line" = "#0000"
"editor.dim" = "#666"
"editor.drag_drop_background" = "#88888855"
"editor.drag_drop_tab_background" = "#11111155"
"editor.focus" = "#CCCCCC"
"editor.foreground" = "$white"
"editor.indent_guide" = "$grey"
"editor.link" = "$blue"
"editor.selection" = "$grey"
"editor.sticky_header_background" = "$black"
"editor.visible_whitespace" = "$grey"
"error_lens.error.background" = "#E06C7520"
"error_lens.error.foreground" = "$red"
"error_lens.other.background" = "#5C637020"
"error_lens.other.foreground" = "#5C6370"
"error_lens.warning.background" = "#E5C07B20"
"error_lens.warning.foreground" = "$yellow"
"hover.background" = "#222"
"inlay_hint.background" = "#55555555"
"inlay_hint.foreground" = "$white"
"lapce.border" = "#000000"
"lapce.button.primary.background" = "#50a14f"
"lapce.button.primary.foreground" = "$black"
"lapce.dropdown_shadow" = "#000000"
"lapce.error" = "$red"
"lapce.icon.active" = "$white"
"lapce.icon.inactive" = "#5C6370"
"lapce.plugin.author" = "#B0B0B0"
"lapce.plugin.description" = "$white"
"lapce.plugin.name" = "#DDDDDD"
"lapce.remote.connected" = "#50A14F"
"lapce.remote.connecting" = "#C18401"
"lapce.remote.disconnected" = "#E45649"
"lapce.remote.local" = "#4078F2"
"lapce.scroll_bar" = "$grey"
"lapce.tab.active.background" = "$black"
"lapce.tab.active.foreground" = "$white"
"lapce.tab.active.underline" = "#528BFF"
"lapce.tab.inactive.background" = "#222"
"lapce.tab.inactive.foreground" = "$white"
"lapce.tab.inactive.underline" = "#555"
"lapce.tab.separator" = "#222"
"lapce.warn" = "$yellow"
"markdown.blockquote" = "#888"
"palette.background" = "$black"
"palette.current.background" = "#222"
"palette.current.foreground" = "$white"
"palette.foreground" = "$white"
"panel.background" = "#222"
"panel.current.background" = "$black"
"panel.current.foreground" = "$white"
"panel.current.foreground.dim" = "#666"
"panel.foreground" = "$white"
"panel.foreground.dim" = "#666"
"panel.hovered.background" = "#333"
"panel.hovered.foreground" = "$white"
"panel.hovered.foreground.dim" = "#666"
"source_control.added" = "#50A14F32"
"source_control.modified" = "#0184BC32"
"source_control.removed" = "#FF526632"
"status.background" = "$black"
"status.foreground" = "$white"
"status.modal.insert" = "$red"
"status.modal.normal" = "$blue"
"status.modal.terminal" = "$purple"
"status.modal.visual" = "$yellow"
"terminal.background" = "$black"
"terminal.black" = "$black"
"terminal.blue" = "$blue"
"terminal.bright_black" = "#555"
"terminal.bright_blue" = "$blue"
"terminal.bright_cyan" = "$cyan"
"terminal.bright_green" = "$green"
"terminal.bright_magenta" = "$magenta"
"terminal.bright_red" = "$red"
"terminal.bright_white" = "#C8CCD4"
"terminal.bright_yellow" = "$yellow"
"terminal.cursor" = "$white"
"terminal.cyan" = "$cyan"
"terminal.foreground" = "$white"
"terminal.green" = "$green"
"terminal.magenta" = "$magenta"
"terminal.red" = "$red"
"terminal.white" = "$white"
"terminal.yellow" = "$yellow"

[ui]
font-family = ""
font-size = 13
icon-size = 0
header-height = 35
status-height = 25
tab-min-width = 100
scroll-width = 10
drop-shadow-width = 0
preview-editor-width = 0
hover-font-family = ""
hover-font-size = 0
trim-search-results-whitespace = true
